# Generated by Django 5.2.14 on 2026-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
