# Generated by Django 5.2.11 on 2026-03-01 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount')], max_length=10)),
                ('value', models.PositiveIntegerField()),
                ('min_cart_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount')], max_length=10)),
                ('value', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('BRAND', 'Brand')], max_length=20)),
                ('scope_ref_id', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('savings_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='catalog.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='promotions.bundle')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'unique_together': {('bundle', 'variant')},
            },
        ),
    ]
